{% set name = "minimal-snowplow-tracker" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: acabf7572db0e7f5cbf6983d495eef54081f71be392330eb3aadb9ccb39daaa4

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - requests >=2.2.1,<3.0
    - six >=1.9.0,<2.0

test:
  imports:
    - snowplow_tracker
    - snowplow_tracker.test
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://www.getdbt.com/
  # The source code is only avaialble her https://pypi.org/project/minimal-snowplow-tracker/#history
  doc_url: https://pypi.org/project/minimal-snowplow-tracker/
  summary: A minimal snowplow event tracker for Python. Add analytics to your Python and Django apps, webapps and games
  description: |
    A minimal snowplow event tracker for Python. Add analytics to your Python and Django apps, webapps and games
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
  skip-lints:
    - missing_dev_url
